homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('results/', views.home_results, name='home_results'),
    path('celeb_detail/<str:value>', views.celeb_detail, name='celeb_detail'),
]

wikiforb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

occupation_list = ['Select an occupation', 'Activist', 'Actor', 'Actress', 'Animator', 'Analyst', 'Athlete',
'Author', 'Band', 'Baseball Player', 'Basketball Player', 'Boxer', 'Businessman', 'Businesswoman', 'Chef', 
'Comedian', 'Composer', 'Cricket Player', 'Cyclist', 'DJ', 'Dancer', 'Designer', 'Director', 'Economist',
'Figure Skaters', 'Film Critic', 'Film Producer', 'Filmmaker', 'Football Analyst', 'Football Player', 
'Golfer', 'Hockey Player', 'Internet Personality', 'Journalist', 'Lobbyist', 'Magician', 
'Mixed Martial Artist', 'Model', 'Motorcycle Racer', 'Musician', 'Pastor', 'Political Analyst', 
'Politician', 'Producer', 'Race Car Driver', 'Radio Host', 'Rapper', 'Reality TV', 'Singer', 'Soccer Player',
'Speaker', 'TV Commercial Cast', 'TV Executives', 'TV Host', 'TV Personality', 'TV Producer', 'TV Show Cast',
'Tennis Player'	, 'Theater', 'Theater Duo', 'Track Athlete', 'Wrestler', 'Writer']

occupation_option = []

for i in range(len(occupation_list)):
    if i == 0:
        occupation_option.append(('', occupation_list[i]))
    else:
        occupation_option.append((occupation_list[i], occupation_list[i]))

class QueryForms(forms.Form):
    name = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class':'form-control', 'id':'name', 'placeholder':'Enter celebrity/event/product name',
            }
        ),
    required = False)

    occupation = forms.CharField(
        widget = forms.Select(
            choices = occupation_option,
            attrs = {
                'class':'form-control', 'id':'occupation',
            }
        ),
    required = False)

    year = forms.IntegerField(
        widget = forms.NumberInput(
            attrs = {
                'class':'form-control', 'id':'name', 'placeholder':'Enter forbes year', 'min':'1999', 'max':'2020',
            }
        ),
    required = False)

    rank = forms.IntegerField(
        widget = forms.NumberInput(
            attrs = {
                'class':'form-control', 'id':'name', 'placeholder':'Enter forbes rank', 'min':'1', 'max':'100',
            }
        ),
    required = False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

homepage/views.py
from django.shortcuts import render
from .forms import QueryForms
from .rdf_query import results_from_local, results_from_dbpedia, results_local_from_name

# Create your views here.
def home(request):
    context = {
        'query_forms' : QueryForms
    }
    return render(request, 'homepage.html', context)

def home_results(request):
    context = {
        'query_forms' : QueryForms
    }
    if request.method == 'POST':
        received_form = QueryForms(request.POST)
        if (request.POST['name'] or request.POST['year'] or request.POST['rank'] or request.POST['occupation']) == "":
            res = ""
        else:
            res = results_from_local(request.POST['name'], request.POST['year'], request.POST['rank'], request.POST['occupation'])
        context['query_forms'] = received_form
        context['query_res'] = res
        return render(request, 'results.html', context)

def celeb_detail(request, value):
    value_rep = value.replace(" ","_")
    response = {"name": value_rep}
    dbpedia_query_res = results_from_dbpedia(response["name"])
    local = results_local_from_name(value)
    dbpedia = dbpedia_query_res[0]

    if(len(dbpedia) != 0):       
        if ('description' in dbpedia):
            response['description'] = dbpedia['description']['value']
        else:
            response['description'] = " - "

        if ('startDate' in dbpedia):
            response['startDate'] = dbpedia['startDate']['value']
        else:
            response['startDate'] = " - "
       
        if ('birthDate' in dbpedia):
            response['birthDate'] = dbpedia['birthDate']['value']
        else:
            response['birthDate'] = " - "
        
        if ('birthPlace' in dbpedia):
            response['birthPlace_link'] = dbpedia['birthPlace']['value']
            response['birthPlace'] = response['birthPlace_link'].split("/")[-1].replace('_', " ")
        else:
            response['birthPlace_link'] = " - "
            response['birthPlace'] = " - "
        
        if ('celebName' in dbpedia):
            response['celebName'] = dbpedia['celebName']['value'].replace('_'," ")

        if ('thumbnail' in dbpedia):
            response['thumbnail'] = dbpedia['thumbnail']['value']  
        
        response['occupation'] = local[0]['occupation']

        response['yearRank'] = []
        for data in local:
            response['yearRank'].append(data['yearRank'])

    return render(request, 'infobox_celeb.html', response)

homepage/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
    <script src="https://www.vantajs.com/dist/vanta.waves.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>Welcome to WikiForb</title>
  </head>
  
  <body>
    <div id="banner">
      <h1>WikiForb</h1>
      <h4>Is a website that provide information about top 100 high-income<h4>
      <h4>celebrities/events/products based on Forbes Global Media from 1999-2020.</h4>
    </div>
    <br><br>

    <form action="{% url 'homepage:home_results' %}" method="POST">
      <h3>Search your Interest</h3>
      {% csrf_token %}
      <div class="form-group">
        <br>
        <label for="name"><b>Name</b></label>
          {{ query_forms.name }}
      </div>
      <div class="form-group">
        <label for="occupation"><b>Occupation</b></label>
          {{ query_forms.occupation }}
      </div>
      <div class="form-group">
        <label for="year"><b>Forbes Year</b></label>
          {{ query_forms.year }}
        <small id="year" class="form-text text-muted">Please enter forbes year interval 1999 to 2020.</small>
      </div>
      <div class="form-group">
        <label for="rank"><b>Forbes Rank</b></label>
          {{ query_forms.rank }}
        <small id="rank" class="form-text text-muted">Please enter forbes rank interval 1 to 100.</small>
      </div>
      <div class="text-right">
        <button type="submit" class="btn btn-primary" >Search</button>
      </div>
    </form>

    <br>
    <footer class="text-center text-white bottom" style="background-color: rgb(38, 106, 161);">    
      <div class="text-center p-3">
        © 2021 Copyright Semweb Group
      </div>
    </footer>

  </body>

</html>

<script> 
  VANTA.WAVES({
  el: "#banner",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 340.00,
  minWidth: 200.00,
  scale: 1.00,
  scaleMobile: 1.00,
  color: 0x5588,
  shininess: 59.00,
  waveHeight: 9.50,
  waveSpeed: 0.50,
  zoom: 1.5})
</script>

homepage/templates/infobox_celeb.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
    <script src="https://www.vantajs.com/dist/vanta.waves.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>About Celebrity</title>
  </head>
  
  <body>
    <div id="banner">
      <h1>WikiForb</h1>
      <h4>Is a website that provide information about top 100 high-income<h4>
      <h4>celebrities/events/products based on Forbes Global Media from 1999-2020.</h4>
    </div>

    <br><br><br><br><br><br>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <p class="celeb-name"><b>{{ celebName }}</b></p>
          <img src="{{ thumbnail }}" class="rounded mx-auto d-block" alt="{{ celebName }}">
        </div>
        <div class="col-6">
          <div class="card detail">
            <div class="card-body">
              <p><b>Forbes Year-Rank : </b></p>
              <ul>
                {% for yr in yearRank %}
                  <li>{{ yr }}</li>
                {% endfor %}
              </ul>
              <p><b>Occupation : </b> {{ occupation }}</p>
              <p><b>Start Date : </b> {{ startDate }}</p>
              <p><b>Birth Date : </b> {{ birthDate }}</p>
              <p><b>Birth Place : </b> <a href="{{ birthPlace_link }}" target="_blank">{{ birthPlace }}</a></p>
              <p><b>Abstract : </b> {{ description }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>


    <br>
    <footer class="text-center text-white bottom" style="background-color: rgb(38, 106, 161);">    
      <div class="text-center p-3">
        © 2021 Copyright Semweb Group
      </div>
    </footer>

  </body>

</html>

<script> 
  VANTA.WAVES({
  el: "#banner",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 340.00,
  minWidth: 200.00,
  scale: 1.00,
  scaleMobile: 1.00,
  color: 0x5588,
  shininess: 59.00,
  waveHeight: 9.50,
  waveSpeed: 0.50,
  zoom: 1.5})
</script>

homepage/templates/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
    <script src="https://www.vantajs.com/dist/vanta.waves.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <title>Result</title>
  </head>
  
  <body>
    <div id="banner">
      <h1>WikiForb</h1>
      <h4>Is a website that provide information about top 100 high-income<h4>
      <h4>celebrities/events/products based on Forbes Global Media from 1999-2020.</h4>
    </div>
    <br><br>
    
    <form method="POST">
      <h3>Search your Interest</h3>
      {% csrf_token %}
      <div class="form-group">
      <br>
        <label for="name"><b>Name</b></label>
          {{ query_forms.name }}
      </div>
      <div class="form-group">
        <label for="occupation"><b>Occupation</b></label>
          {{ query_forms.occupation }}
      </div>
      <div class="form-group">
        <label for="year"><b>Forbes Year</b></label>
          {{ query_forms.year }}
        <small id="year" class="form-text text-muted">Please enter forbes year interval 1999 to 2020.</small>
      </div>
      <div class="form-group">
        <label for="rank"><b>Forbes Rank</b></label>
          {{ query_forms.rank }}
        <small id="rank" class="form-text text-muted">Please enter forbes rank interval 1 to 100.</small>
      </div>
      <div class="text-right">
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
    </form>
    <br>

    <hr><br>
    <h3>Search Results</h3>
    <br>
    <div class="container">
      <div class="row">
        {%  if query_res|length != 0 %}
          {% for celeb in query_res %}
            <div class="col-4">
              <a class = "card-link" href="{% url 'homepage:celeb_detail' celeb.celebName %}">
              <div class="card" id="card-celeb-result">
                <div class="card-body">
                  <h3 class="card-title"><b>{{ celeb.celebName }}</b></h3>
                  <p class="card-occupation"><b>Occupation :</b> {{ celeb.occupation }}</p>
                  <p class="card-year"><b>Forbes Year :</b> {{ celeb.year}}</p>
                  <p class="card-rank"><b>Forbes Rank :</b> {{ celeb.rank }}</p>
                </div>
              </div></a>
            </div>  
          {% endfor %}
        
        <div >
          {%  elif query_res|length == 0 %}
          <h3 style="text-align:center;"><b>Result Not Found</b></h3>
          {% endif %}
        </div>
        
      </div>
    </div>
    




    <footer class="text-center text-white bottom" style="background-color: rgb(38, 106, 161);">    
      <div class="text-center p-3">
        © 2021 Copyright Semweb Group
      </div>
    </footer>

  </body>

</html>

<script> 
  VANTA.WAVES({
  el: "#banner",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 340.00,
  minWidth: 200.00,
  scale: 1.00,
  scaleMobile: 1.00,
  color: 0x5588,
  shininess: 59.00,
  waveHeight: 9.50,
  waveSpeed: 0.50,
  zoom: 1.5})
</script>